---
dist: trusty
sudo: required
language: python
matrix:
  allow_failures:
    - os: osx

os:
  - linux
  - osx

before_install:
  # Make sure everything's up to date.
  - cd /tmp 
  - git clone https://github.com/sstephenson/bats.git
  - cd /tmp/bats
  - sudo ./install.sh /usr/local

install:
  - env
  - cd $TRAVIS_BUILD_DIR/example 
  - bash -x ./travis-setup-basic.sh

script:
  - cd $TRAVIS_BUILD_DIR/tests
  - ./common.sh
  - ./ansible-version.sh
  - ./various_runs.sh
  # Run setup again with full path Basic
  - bash -x $TRAVIS_BUILD_DIR/example/travis-setup-basic.sh
  - ./installation.sh
  - ansible --version
  # Run setup again with full path setup user
  - bash -x $TRAVIS_BUILD_DIR/example/travis-test-setup-user.sh
  - ./common_setup_user.sh